#! /bin/bash

# Command Args
command=${0}
subcommand=${1}

# User Configurable Params (prefixed by `HOMEPORTS_`)
HP_DIR=${HOMEPORTS_DIR:-$HOME/.homeports}
HP_EDITOR=${HOMEPORTS_EDITOR:-code}
HP_SHELL=${HOMEPORTS_SHELL:-bash}

set -u

# Internal Use Params
HP_USER_HOME=${HP_DIR}/home

hp-help() {
cat << __EOM__
Management user home
Usage: homeports <command> ...

Entry Management Commands:
  add <file> [<file> ...]
          : register files to be under homeports management (with commit)
  delink  : replace all symlinks into reguler files
  edit    : open homeports directory by HOMEPORTS_EDTOR=${HP_EDITOR}
  link    : create symlinks
  links   : list all symlinks
  list    : list all registered entries
  rm [<entry> ...]
          : unregister the entry (with commit)
  unlink  : remove all symlinks

Repository Management Commands:
  commit  : commit changes
  pull    : pull updates from remote
  push    : push updates to remote
  remote  : show remote information

Utility Commands:
  doctor  : check dependencies
  env     : show configurable ENVs
  find    : find all links pointing the repository under $HOME
  help    : show this help
  init    : clean all registered contents
  log     : show commit log
  sh      : enter homeports shell by HOMEPORTS_SHELL=${HP_SHELL}
  update  : update homeports
__EOM__
}

# Entry Management Commands
# -------------------------

hp-add() {
  new_entries=""
  for src in "$@"; do
    echo "$src"
    src_path_from_home=$(realpath --relative-base ~ "$src")
    dest_dir=$(dirname "$HP_USER_HOME/$src_path_from_home")
    mkdir -p "$dest_dir"
    cp -r "$src" "$dest_dir"
    echo "copy ~/${src_path_from_home} -> ${dest_dir}"
    new_entries+=$(basename "$src"),
  done;

  cd-home
  git add .
  git commit -m "Add ${new_entries%?}"
}

hp-delink() {
  hp-list | while IFS= read -r entry; do
    link=$HOME/$entry
    if is-managed-symlink "$link"; then
      echo "Delink $link"
      rm "$link"
      cp -r "$HP_USER_HOME/$entry" "$link"
    fi
  done
}

hp-edit() {
  $HP_EDITOR "$HP_USER_HOME"
}

hp-link() {
  declare F_FORCE
  while getopts fh OPT; do
    case $OPT in
      f) F_FORCE=1 ;;
      h) help-exit ;;
     \?) help-exit ;;
    esac
  done

  hp-list | while IFS= read -r entry; do
    if ! has-symlink "$entry"; then
      real="${HP_USER_HOME}/${entry}"
      link="${HOME}/${entry}"

      # Check existence and treat force option
      if [ -f "${link}" ]; then
        if [ -n "${F_FORCE}" ]; then
          echo "Remove ${link}"
          rm "${link}"
        else
          continue
        fi
      fi

      echo "Craete symlink: ${link} -> ${real}"
      ln -s "${real}" "${link}"
    fi
  done
}

hp-link-help() {
  cat << __EOF__
  Usage: ${command} ${subcommand} [-f]
  Options:
    -f : Force replace
__EOF__
}

hp-links() {
  hp-list | while IFS= read -r entry; do
    link="$HOME/$entry"
    if is-managed-symlink "$link"; then
      print-link "$link"
    fi
  done
}

hp-list() {
  cd-home
  find . -type f | cut -sd / -f 2- | grep -v .git
}

hp-rm() {
  cd-home
  git rm -r "$@"
  git commit -m "Remove $*"
}

hp-unlink() {
  confirm "It removes all symlinks. Continue?"
  hp-list | while IFS= read -r entry; do
    link=$HOME/$entry
    if is-managed-symlink "$link"; then
      echo "Remove ${link}" 
      rm "$link"
    fi
  done
}

# Repository Management Commands
# ------------------------------

hp-commit() {
  cd-home
  entries=$(git diff --name-only | cut -sd / -f 2- | tr '\n' ' ')
  git add .
  git commit -m "Edit ${entries}"
}

hp-pull() {
  cd-home
  git pull
}

hp-push() {
  cd-home
  git push
}

hp-remote() {
  cd-home
  git fetch
  echo "Repository:"
  git remote -v
  echo "Diff:"
  git diff origin/master
}

# Utility Commands
# ----------------

hp-doctor() {
  if ! type realpath &> /dev/null; then
    echo "Missing a command 'realpath', it's packaged in GNU 'coreutils'"
  fi
}

hp-env() {
  echo "HOMEPORTS_DIR    =${HP_DIR}"
  echo "HOMEPORTS_SHELL  =${HP_SHELL}"
  echo "HOMEPORTS_EDITOR =${HP_EDITOR}"
}

hp-find() {
  links=$(find "$@" -lname '*.homeports/home/*')
  for link in $links; do
    print-link "$link"
  done
}

hp-log() {
  cd-home
  git log "$@"
}

hp-sh() {
  echo "Enter ${HP_DIR}"
  cd-home
  $HP_SHELL
}

hp-update() {
  cd "$HP_DIR" || exit
  git pull
}

# Utilities
# ---------

cd-home() {
  cd "$HP_USER_HOME" || exit
}

confirm() {
  read -p "$1 [y/N]: " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
  fi
}

print-link() {
  target=$(realpath "$1")
  echo "${1} -> ${target}"
}

is-managed-symlink() {
  path=$(realpath "$1")
  if [ "${path/$HP_USER_HOME}" = "${path}" ]; then # detect is-not-substring
    return 1
  fi
  return 0
}

has-symlink() {
  is-managed-symlink "${HOME}/${1}"
}

help-exit() {
  "hp-${subcommand}-help"
  exit 1;
}

# Main Script
# -----------

case $subcommand in
    "" | "-h" | "--help")
        hp-help
        ;;
    *)
        shift
        "hp-${subcommand}" "$@"
        if [ $? = 127 ]; then
          hp-help
        fi
        ;;
esac